### ISSUE TITLE
Add files shorcuts

### ISSUE THREAD

**Issue by ericfranz** [OSC/bc_js_filepicker#1]
The directory shortcuts should be on the left of the dialog, and by default should be the first directory:

![screen 2019-07-22 at 2 37 16 PM](https://user-images.githubusercontent.com/512333/61656197-3a012d80-ac8e-11e9-9930-a922639f1611.png)

When I opened it, I was on the root file system and couldn't find my home directory.

**Comment by MorganRodgers** [comment]
The current implementation always defaults to the root dir on the first load, it's something that I want to fix before the release is 100% ready.

**Comment by MorganRodgers** [comment]
Added in 5e723a326c324795813b13129ff7638d56a76243

<img width="610" alt="file_favorites" src="https://user-images.githubusercontent.com/13316545/61732189-58922200-ad7d-11e9-83ff-c361b501f4a8.png">

**Comment by MorganRodgers** [comment]
Added in [v0.1.0](https://github.com/OSC/bc_js_filepicker/releases/tag/v0.1.0).
