### ISSUE TITLE
Issue with filepicker/JS

### ISSUE THREAD

**Issue by ahkumar** [OSC/bc_js_filepicker#168]
Dear OSC Team,

I have downloaded latest form.js and added the following to my jupyter-notebook batch_connect app. 

  working_dir:
    label: "Working Directory"
    data-filepicker: true
    data-target-file-type: dirs  
    readonly: false
    help: "Select your project directory; defaults to $HOME"

I see the blank input box, and when I click on it or double click on it I don't see the file browser pop-up. Looking at the error on the page I see the following. Any idea how can I fix this? 

![image](https://user-images.githubusercontent.com/12764775/156798303-b988ed50-9071-4485-84f1-b097a924c00b.png)

Thanks,
Amit

**Comment by ahkumar** [comment]
Also wanted to add there is no Select button, which would be nice to add instead of clicking on input box. Demo screenshot shows select button I wonder if this requires additional jscript to link it to the input box?

**Comment by johrstrom** [comment]
What version of OnDemand are you on? There's a backward compatibility issue between 1.8 and 2.0.

**Comment by ahkumar** [comment]
Hi Jeff it is v1.8.20

**Comment by johrstrom** [comment]
There ya go, use this release instead.

https://github.com/OSC/bc_js_filepicker/releases/tag/v0.4.7

**Comment by ahkumar** [comment]
Thank you Jeff. I downloaded v0.4.7 form.js ;  Cleared my browser cached data and restarted PUN, but no success:

![image](https://user-images.githubusercontent.com/12764775/156847826-181c3009-5263-4174-8ed3-d78fdbeeacb2.png)

Any idea?

**Comment by johrstrom** [comment]
Hi, sorry for the delay this should be fixed now in version 3.0.1 - you can pull the form.js from here: https://github.com/OSC/bc_js_filepicker/releases/tag/v3.0.1
