### ISSUE TITLE
Toggle view select [file,directory] based on what you have selected

### ISSUE THREAD

**Issue by johrstrom** [OSC/bc_js_filepicker#17]
As requested from [discourse](https://discourse.osc.edu/t/form-yml-file-browser-object/427/24) we'd like to have the button to choose the file change text depending on whether it's a directory or file.  So if you've highlighted a directory it would show `Select Directory` and same with a file.

**Comment by ericfranz** [comment]
In the Discourse topic, Jean-Marie is actually asking for an ability to configure the file picker, with a data attribute, to specify whether when you open it you are selecting a file or a directory. I clarify this in https://github.com/OSC/bc_js_filepicker/issues/18. Message me on Slack if you disagree and we can resolve and update the GitHub issues appropriately.
