### ISSUE TITLE
can't select favorites

### ISSUE THREAD

**Issue by stdweird** [OSC/bc_js_filepicker#206]
i have OOD 2.0.29 and filepicker 1.0.0. 

the picker is for selecting directories and i have bunch of favorites defined.

however, when i select a favorite, and then press the select button, nothing is done.
i need to select one of the subdirs first. and also strange (or even buggy?) i can't select the `.` or `..` dirs. 

this makes the favorites a bit useless in our case, as i can't select the favorites themself

**Comment by stdweird** [comment]
there was nothing in the release notes of v3 about this, so i haven tried (and it's not trivial for me to update anyway)

**Comment by stdweird** [comment]
if you have some vague idea where i should look, i can give it a try myself. probably something simple is missing, but i'm not sure where to start looking

**Comment by stdweird** [comment]
i only now also see this is a dupe of #204

**Comment by johrstrom** [comment]
here's the event handler for when things are clicked. that may be a starting point.

https://github.com/OSC/bc_js_filepicker/blob/f854d9258baf570c6b0f375badcfa975722b29fd/src/components/file_picker.vue#L197

**Comment by stdweird** [comment]
@johrstrom i think the fix might be simple: when a menu is clicked (but most likely also when an entry is doubleclicked), the `this.staged_value` should be set to `this.path`.
i'll test this, but i can't easily think of a reason why not to do this.

with current code, it looks like if eg you select a file, and then later click the menu or double click a directory entry; the last entry that was clicked is the one that is still considered as "selected"; even when the viewer is showing something entirely different. that makes no sense imho.

**Comment by stdweird** [comment]
@johrstrom i confirm the PR fixes the behaviour.

**Comment by stdweird** [comment]
@johrstrom how odd. the patch is against current master, so there is no way in the code that clikcing the menu would set the staged_value. anyway, will give it a try

**Comment by stdweird** [comment]
@johrstrom with 3.0.1 menuclick does not work, but doubleclick does seem to work (still odd, maybe i mistested it in 1.0.0 as well). see webm screencast https://we.tl/t-AWlQosNQ71

**Comment by stdweird** [comment]
i retested it with 1.0.0. doubleclick indeed works (maybe it always triggers a single click?)
anyway, i adapted the PR to only fix the favorites
