### ISSUE TITLE
Why is the release file so large?

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/bc_js_filepicker#3]
The release current weighs in at 251k. The reason that the file is so very large is that it is bundling jQuery and the Vue runtime as a convenience to speed adoption.

If desired the dependency on jQuery could be removed, and Vue's runtime could be moved to either a CDN or a separate file.

**Comment by ericfranz** [comment]
Maybe a release should include a "dashboard build"

- jQuery could be removed by just using https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector; or use the Dashboard's jQuery; but plain old JavaScript is probably good enough
- Boostrap could also be omitted, since that is included in the Dashboard already

**Comment by MorganRodgers** [comment]
I'll look at using the querySelector to replace jQuery.

I had originally tried to use the Dashboard provided version by declaring jQuery as a dependency external to the bundle, but the application failed to work without any errors that I could see. Likewise I was having problems getting the Bootstrap modal to work without an explicit Bootstrap include.

**Comment by MorganRodgers** [comment]
I have a prototype that replaces jQuery as a direct dependency, but it's a bit of a waste because it complicates the code and Bootstrap requires jQuery for modals to work and we do not appear to be shipping the modal module. However if I specifically include only the modal module the bundle size drops significantly.

**Comment by MorganRodgers** [comment]
Improved in [v0.1.0](https://github.com/OSC/bc_js_filepicker/releases/tag/v0.1.0). It is possible to stop using Bootstrap's JS for creating the modal and switch to a Vue-only modal. That would likely result in a smaller bundle, and may be pursued in future versions.
