### ISSUE TITLE
scroll bar should only apply to list of directories/files

### ISSUE THREAD

**Issue by johrstrom** [OSC/bc_js_filepicker#92]
One annoying thing for me about this is if I click on something I want, the select button isn't just there. I have to scroll to the bottom to see it. It'd be nice if the scroll bar were only for scrolling through directories & files and the header, footer and side list all stayed in the same position which is always viewable.

**Comment by stdweird** [comment]
@johrstrom just to let you know,  i am running OOD 2.0.29 with filepicker 1.0.0 and i don't have this behaviour (i was porbably fixed along the way)
